# Generated by Django 6.0.6 on 2026-06-06 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=100)),
                ('manager_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
    ]
